### ISSUE TITLE
There is no way to delete an address

### ISSUE THREAD

**Issue by nanostos** [bitrequest/bitrequest.github.io#11]
This is in the context of using Bitrequest for an XMR physical point of sale solution.

There is no way to delete an address, from what I can see. Only an option for '+ Add address' and then the ability to untick the old address. Not a big deal in practice, but removing incorrect addresses is helpful to avoid possible mistakes (esp when app is shared among rotating staff).

**Comment by bitrequest** [comment]
There is an extra menu when clicking the green button on the right (Everything green is clickable)

<img width="574" alt="Scherm­afbeelding 2023-02-23 om 10 21 04" src="https://user-images.githubusercontent.com/47079460/220868407-6edfedfb-a19e-4622-af5a-a166cfdd3846.png">

**Comment by nanostos** [comment]
Ah great. Helpful menu items there! I guess my only comment then would be that this is not so obvious and that it seemed at first to function only as a handle to drag and change address order.

**Comment by bitrequest** [comment]
Yes it does both. It's a bit of a trade-off for keeping the design as clean as possible.

**Comment by nanostos** [comment]
You're the creator and I'm just some random guy, but I'll just make my suggestion anyway :)

I would have found it unambiguous and immediately intuitive if it had the conventional six/eight dot icon on the left side, for grab and reorder, like in the image below. Then on the right it can have either a gear or spanner icon, which is very obvious to indicate 'options'/'settings'. I seriously did spend a while looking through the app to find a way to delete addresses and I wouldn't have realized I can tap that button, even though I have used it to reorder addresses! Maybe I'm just dumb, but then again, lots of people are dumb, haha...

![image](https://user-images.githubusercontent.com/79636894/221333830-877ab6ee-8e34-4f4d-adce-8ee8664bf6f9.png)

**Comment by bitrequest** [comment]
I am gonna leave it like it is for now because i don't see it as a major issue unless there's bigger demand for it.
