### ISSUE TITLE
Feature request: better screen scaling for iPad landscape mode

### ISSUE THREAD

**Issue by nanostos** [bitrequest/bitrequest.github.io#15]
This is in the context of using Bitrequest for an XMR physical point of sale solution.

iPads are usually used in landscape mode, which narrows the screen space when the keyboard is displayed. It would be nice if the layout were optimised to allow the request window to fit into the screen space above the keyboard. Currently the usage is quite clumsy in practice. Cashier opens request window, but keyboard then obscures amount field. So, they scroll up to see that they are entering the amount correctly, but this then obscures the QR code. So, they have to close the keyboard to display the QR for scanning. Rinse and repeat for next customer.

**Comment by bitrequest** [comment]
I tried real hard to make it fit every screen. Bitrequest is just one responsive web app that has to fit all screens. No seperate apps for specific devices. Benefits are i only have to update once for all apps.
My personal ipad is a bit bigger and has no issues. And a lot of apps only support portrait. So when a merchant runs in this issue i suggest to tilt the screen to portrait ;-)
For now unless bitrequest gets more used and there's more demand i might reconsider.
