### ISSUE TITLE
Feature request: remove the need to manually enter a decimal when entering the fiat amount

### ISSUE THREAD

**Issue by nanostos** [bitrequest/bitrequest.github.io#16]
This is in the context of using Bitrequest for an XMR physical point of sale solution.

Card machines work this way to save time since it is common for values to contain cents. For a $25.95 order, the cashier should just have to enter [2] [5] [9] [5], or for a $5 order [5] [0] [0]. I have observed that it throws cashiers a bit off when they use Bitrequest.

**Comment by bitrequest** [comment]
What if you want to enter eg 550 euro?

**Comment by nanostos** [comment]
> What if you want to enter eg 550 euro?

Then it would be [5] [5] [0] [0] [0]. Have a look next time someone enters the amount into a card machine (where it's not connected to a register that autofills it): this is always the way they do it. I wouldn't take it upon myself to judge which way is better, but I've just observed that this is the standard that seems to prevail.

**Comment by bitrequest** [comment]
That doesn't make much sense to me honestly, gonna leave it like it is.
Maybe it's because i'm dutch :-)

**Comment by trasherdk** [comment]
@nanostos is right. 

Even ATM's had this, until a few years back, they dropped decimals completely. They don't spit out coins anyway :smile:

**Comment by nanostos** [comment]
> @nanostos is right.
> 
> Even ATM's had this, until a few years back, they dropped decimals completely. They don't spit out coins anyway 😄

@trasherdk Right, in that case it wouldn't make sense, though it does still illustrate the commonality of the practice. But most stores/cafes/restaurants do actually price things with cents included (the $X.95 or $X.99 template especially). So, the idea is just that you express every value as cents, and the decimal appears where it's meant to be to display the amount in dollars/euros/etc. Sort of like auto-filling the '/' when entering a date, so the user doesn't have to manually type the '/'.

But as I said before, my main comment wasn't about which way is better. It was about what store clerks are happen to be accustomed to, which is the more important point. But I can also appreciate that the dev might not be as motivated to make a change unless there's similar feedback from more users.

**Comment by trasherdk** [comment]
@nanostos  Again, I agree :laughing: 

App's like this should target the end-user. Not the dev, who presumably thinks very differently, compared to some low paid till operator.

**Comment by bitrequest** [comment]
Unfortunately too complicated to implement with all the real time fiat / crypto conversions going on, outweigh the benefits in my opinion.
