### ISSUE TITLE
Monero unable to have multiple requests open at one time

### ISSUE THREAD

**Issue by t-900-a** [bitrequest/bitrequest.github.io#2]
Noticed you're using main addresses for the monero integration.

Due to this, your application is limited in it's ability to have multiple requests open at one time, because you don't want to confuse requests with one another.

Using integrated addresses should help identify the incoming transaction to a specific request, thus allowing you to have multiple requests open at one time.

Really like this project, in that you are compatible with so many chains

**Comment by bitrequest** [comment]
Thanks for the suggestion! I will look into this.

**Comment by bitrequest** [comment]
Hey, I have implemented integrated addresses for monero!
Maybe you could test and see if it's working. It's only enabled when you enter a bip39 passphrase.
https://github.com/bitrequest/bitrequest.github.io/commit/769f241558f9e69fa08e40892af0507b82cda6f9

**Comment by bitrequest** [comment]
Full support for Monero integrated addresses: https://github.com/bitrequest/bitrequest.github.io/commit/ad64067c82b1577a9f963325d591991ee2c770e7

**Comment by t-900-a** [comment]
Noting that bitrequest uses the mymonero rpc, therefore subaddresses are not available and integrated addresses have to be used.

https://github.com/bitrequest/bitrequest.github.io/blob/63fadfdedd7520e43556ba94ee6dedf763ba749a/assets/js/bitrequest_config.js#L1326

**Comment by bitrequest** [comment]
Subaddresses are fully integrated in bitrequest already but i have disabled them because the mymonero rpc doesn't support them. I can enable subaddresses later if  i find an rpc / api that supports them.
Integrated addresses work perfectly for now and are very useful for monitoring requests. I wish other coins had this functionality too. Soo i would definitely vote against deprecation.

**Comment by t-900-a** [comment]
https://twitter.com/devin_pearson/status/1433142222145396742

MyMonero should have subaddress support soon.
