### ISSUE TITLE
Banano?

### ISSUE THREAD

**Issue by benkaiser** [bitrequest/bitrequest.github.io#4]
Are there any plans to support banano currency? Super low priority, but would be fun: https://banano.cc/

**Comment by bitrequest** [comment]
I am planning to add more payment focussed crypto's in the future. There need to be public api and websocket available to verify transactions. So if there's something like https://api.nanos.cc out there for banano i will definetly consider it.

**Comment by benkaiser** [comment]
Yeah I had a look the other day and couldn't find someone that hosts an API for it yet. Might be best to leave that until a good one is available.
