### ISSUE TITLE
Scroll bars visible

### ISSUE THREAD

**Issue by benkaiser** [bitrequest/bitrequest.github.io#6]
It appears when the dialog launches that both horizontal and vertical scrollbars are shown. Is this an easy fix?

<img width="1658" alt="Screen Shot 2021-08-05 at 1 09 21 am" src="https://user-images.githubusercontent.com/608054/128206023-eb77e300-e751-4a77-8c1f-661de0fff827.png">

Is it as simple as adding this CSS?
```
#payment {
  overflow: hidden;
}
```

**Comment by bitrequest** [comment]
Yep, seem like it is, thanks!
Edit: No it's not that simple. You need the scrollbars on smaller windows.
The problem is why the scrollbars are there on a bigger window.

**Comment by bitrequest** [comment]
I fixed this by hiding the horizontal scrollbar and hiding the vertical scrollbar when windowheight is greater then 800px:
https://github.com/bitrequest/bitrequest.github.io/blob/master/assets/styles/media.css#L294
