### ISSUE TITLE
Numpad numbers don't work on the web app

### ISSUE THREAD

**Issue by leonidasmark** [bitrequest/bitrequest.github.io#7]
Typing the amount for a money request on PC (Windows 11, Microsoft Edge) using the numpad numbers on the keyboard doesn't work.
Using the numbers on the top of the keyboard works.

**Comment by bitrequest** [comment]
[Fixed](https://github.com/bitrequest/bitrequest.github.io/commit/b6427d16e6cd62f60da14b3133dbd462f92e1e63)
