### ISSUE TITLE
Where is the latest source code for io.bitrequest.app?

### ISSUE THREAD

**Issue by emanuelb** [bitrequest/bitrequest.github.io#8]
I am looking for the source-code of io.bitrequest.app on google-play
https://play.google.com/store/apps/details?id=io.bitrequest.app

to test for reproducible-builds as part of walletscrutiny project https://walletscrutiny.com/

this repo looked like close-match, but looks like it only contain code for the web app and not for the mobile apps

please publish the code for android app io.bitrequest.app as well with build instructions on how to build it

**Comment by bitrequest** [comment]
Working on it: https://github.com/bitrequest/native  
Just have to figure out how to do this the right way. I'll keep you updated.

This repo is the main PWA app.
Both Android and IOS app use webview to show it's contents.

**Comment by bitrequest** [comment]
They are both released: https://github.com/bitrequest/native
