### ISSUE TITLE
Request to support GRS

### ISSUE THREAD

**Issue by gruve-p** [bitrequest/bitrequest.github.io#9]
What are the possibilities to add Groestlcoin?

**Comment by bitrequest** [comment]
It's possible if you can point me to a public blockchain and websocket API

**Comment by gruve-p** [comment]
symbol: grs
name: groestlcoin

api:
https://blockbook.groestlcoin.org (https://github.com/trezor/blockbook/blob/master/docs/api.md)
https://blockchair.com/groestlcoin (https://blockchair.com/api/docs)
https://esplora.groestlcoin.org/ (https://github.com/Groestlcoin/esplora/blob/master/API.md)
https://chainz.cryptoid.info/grs/ (https://chainz.cryptoid.info/api.dws)

**Comment by gruve-p** [comment]
Do you need anything else?

**Comment by bitrequest** [comment]
Thanks, could you explain what the benefit of GRS is over coins that are already supported?

**Comment by gruve-p** [comment]
GRS is a bitcoin fork similar to Litecoin, Dogecoin and Bitcoin Cash however GRS was the first coin to implement SegWit, Taproot and Lightning Network.  GRS is always up to date with upstream releases

**Comment by bitrequest** [comment]
To be honest, i don't think adding GRS is gonna be a priority any time soon.
